### ISSUE TITLE
Cant find KnownFolders.PictureLibrary in the real disk?

### ISSUE THREAD

**Issue by YingkitTse** [ms-iot/Facial-Recognition-Door#12]
Hi all,

a interesting question: Where is the real path of KnownFolders.PictureLibrary ?

Because I cant find this folder in my sdcard, all sections, all folders...

and I want to copy those pics from sdcard to my computer.

Thx! XD

**Comment by IoTGirl** [comment]
Hi XD,
There is a sample application that shows how to use this folder in your application on Hackster at [https://www.hackster.io/cubiclezombie/win-10-iot-core-usb-camera-upload-images-to-azure-storage-e6c294](https://www.hackster.io/cubiclezombie/win-10-iot-core-usb-camera-upload-images-to-azure-storage-e6c294) 
This folder should have a similar path to the one on your Windows 10 PC but likely you will want to use the Public folders.  For example if I open my web console to my RPi running IoT Core I see User Files with three directories; CameraRoll, Documents & LocalAppData.  
Sincerely,
IoTGirl
