### ISSUE TITLE
Project won't build when following instructions from Hackster.IO

### ISSUE THREAD

**Issue by WillemMali** [ms-iot/Facial-Recognition-Door#6]
Hi,

I cloned the project, set up remote debugging for the `FacialRecognitionDoor` project, set it as the startup project, changed the Project Oxford access key to my own, hit the debug on remote machine button and then I got this:

```
The type 'IAsyncOperation<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime'.
```

A 123 times at different places through the code and with `IAsyncOperation` swapped out for `IAsyncActionWithProgress`, `IAsyncOperationWithProgress` etc.

Do you have any clue as to what this could be? I just installed the Windows 10, 8.1 and UWP SDK to test this project. I'm running Visual Studio Community Edition fully updated, have had it installed for a month. If there's anything I could do to help fix this I'll be available.

**Comment by mazudo** [comment]
Sounds like you may not have the latest required VS studio and SDKs.  Can you make sure to follow all the VS setup steps here? https://developer.microsoft.com/en-us/windows/iot/Docs/GetStarted/rpi3/sdcard/stable/getstartedstep3.  Note, you need to do a custom install and select Universal Windows App Development Tools > Tools and Windows SDK.

**Comment by mazudo** [comment]
Solution posted above, so I am closing this for now.  Please let me know if it still doesn't work for you.
